---
title: "pairing over different conditions"
author: "Wael Kamel"
date: "28/09/2021"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  Visualize the feature-distribution of different genes/proteins (intestity, reads, arbitrary units, etc) over different conditions with different color scales

```{r}
library(tidyverse)
library(ggrepel)
library(ggnewscale)

# loading your data for example


paired_data = as.data.frame(read.table("paired_data.txt", sep="\t",header=TRUE))

# data consists mersurment of certain feature (X) over two conditions Untreated and Treated for a number of 

head(paired_data, 10)
paired_data$group<- factor(paired_data$group ,levels=c("Untreated","Treated"))


# ploting the outline of the plot

paired_data.svg=ggplot(paired_data , aes(x= group, y= featuresX_values)) +
  geom_line(aes(group = gene_no), size=0.2, alpha= 0.5)+
  geom_point(size= 4, color="white" )+
  geom_point(shape = 1,size = 4.2,colour = "black")+
  theme_classic()
paired_data.svg= paired_data.svg+ 
  geom_label_repel( force = 0.5,nudge_x  = 0.25,direction = "y",hjust  = 0,segment.size= 0.1,segment.alpha = 0.3,
                    size= 2,aes(label=ifelse(group=="Treated", as.character(gene_no), "")))

paired_data.svg

#we want to have two different color scales, one for each conditions. first we will add one, using geom_point as a filler and standard scale_color_gradientn

paired_data.svg= paired_data.svg+
  geom_point(data = subset(paired_data, group =="Treated"), aes(color = featuresX_values), size=4)+
  scale_color_gradientn(colors = c("#e7e1ef","#67001f"))


paired_data.svg
# to add the second color scale, this is the tricky part and we use  new_scale_color() from (ggnewscale),  which made it very easy
paired_data.svg= paired_data.svg+
  new_scale_color() +
  geom_point(data = subset(paired_data, group =="Untreated"), aes(color = featuresX_values), size=4)+
  scale_color_gradientn(colors = c("#08306b","#c6dbef"))

# here is how it looks
paired_data.svg



```
